apiVersion: v1
kind: Pod
metadata:
  name: redshift-test
spec:
  containers:
  - name: redshift-test  
    image: postgres:13
    command: ["sleep", "3600"]
  restartPolicy: Never
  deployment_service:  
    repository: rudderlabs/deployment-service
    tag: v1.4.0
  deployment_service_duplicate:
    repository: rudderstack/deployment-service
    version: v1.2.0
  deployment_service_master:
    image: rudderlabs/deployment-service:master
  config_backend:
    image: rudderstack/rudder-config-be
    version: v2.0.0