name: build-artefacts

on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      tag:
        required: false
        type: string
    secrets:
      registry_username:
        required: true
      registry_password:
        required: true
      
jobs:
  build-docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.registry_username }}
          password: ${{ secrets.registry_password }}
      - 
        name: Set the tag
        run: |
          if [ -z "${{ inputs.tag }}" ]
          then
           echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi

      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{secrets.registry_username}}/${{inputs.image_name}}:${{env.final_tag}}