name: Snyk container scan and monitor

on:
  workflow_call:
    secrets:
      SNYK_TOKEN:
        required: true
      SNYK_MONITOR_TOKEN:
        required: true

jobs:
  extract_images_and_scan:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16

    - name: Install dependencies
      run: npm install yaml @octokit/rest js-yaml

    - name: Get YAML changes
      run: |
        node .github/scripts/get-yaml-diff.js > yaml_diff.txt
        echo "DIFF_FILE=${GITHUB_WORKSPACE}/yaml_diff.txt" >> $GITHUB_ENV
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run image registry diff script and save output
      run: |
        node .github/scripts/extractImageFromYaml.js > images_list.txt
        echo "IMAGES_FILE=${GITHUB_WORKSPACE}/images_list.txt" >> $GITHUB_ENV

    - name: Install Snyk CLI
      run: npm install -g snyk@latest

    - name: Authenticate Snyk CLI
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    - name: Install jq
      run: sudo apt-get install jq

    - name: Print contents of yaml_diff.txt
      run: cat $DIFF_FILE

    - name: Print contents of images_list.txt
      run: cat $IMAGES_FILE


    - name: Run Snyk scan script
      run: |
        node .github/scripts/snyk_container_scan.js > critical_images.txt
      env:
        DIFF_FILE: ${{ env.DIFF_FILE }}
        IMAGES_FILE: ${{ env.IMAGES_FILE }}
        DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        SNYK_MONITOR_TOKEN: ${{ secrets.SNYK_MONITOR_TOKEN }}

    - name: Comment on PR if vulnerabilities found
      uses: actions/github-script@v5
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          const fs = require('fs');
          const lines = fs.readFileSync('critical_images.txt', 'utf8').split('\n').filter(Boolean);
          if (process.env.VUL_FOUND === 'true') {
            let body = 'The following images have vulnerabilities:\n\n';
            let currentImage = '';
            for (const line of lines) {
              if (line.includes(' : ')) {
                currentImage = line.split(' : ')[0];
                body += `${currentImage}:\n`;
              } else {
                body += `- ${line}\n`;
              }
            }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: body,
            });
          }